spring.application.name=demoproject
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.web.resources.static-locations=classpath:/static/, file:C:/Users/user/Desktop/demoproject/src/main/resources/static/
server.port=9090
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=demo
spring.datasource.password=demo123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

logging.level.root=info
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
logging.level.org.springframework.security=DEBUG

file.upload-dir=C:/Users/user/Desktop/demoproject/src/main/resources/static/uploads/

spring.devtools.restart.enabled=true

server.servlet.session.timeout=30m